# Async adapter only works within the same process, so for manually triggering cable updates fr>
# and seeing results in the browser, you must do so from the web console (running inside the de>
# not a terminal started via bin/rails console! Add "console" to any action or "" in any view
# to make the web console appear.
development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day